import type { SavedPreset, SophiaSettings, StateAssignments, VoiceState } from "./types";

export const defaultSettings: SophiaSettings = {
  shapeType: "torus",
  majorRadius: 0.58,
  tubeRadius: 0.178,
  showTube: true,
  p: 2,
  q: 3,
  organic: 0.13,
  asymmetry: 0,
  aperture: 0,
  breathing: 0.035,
  knotness: 0,
  attentionDot: false,
  warningAccent: false,

  pivotX: 0,
  pivotY: 0,
  pivotZ: 0,

  bend: 0,
  bendAxis: "z",
  bendX: 0,
  bendY: 0,
  bendZ: 0,
  animateBend: false,
  taper: 0.12,
  taperAxis: "x",
  animateTaper: false,
  stretch: 1,
  stretchAxis: "x",
  compress: 0,
  twist: 0,
  twistAxis: "y",
  animateTwist: false,
  waveAmount: 0,
  waveAxis: "x",
  waveSpeed: 0.8,
  animateWave: true,
  noise: 0.035,
  noiseScale: 1.6,
  animateNoise: true,
  revolve: 0,

  orientX: 12,
  orientY: -8,
  orientZ: -5,
  speed: 0.45,
  orbitX: false,
  orbitY: true,
  orbitZ: false,
  orbitSpeedX: 0.12,
  orbitSpeedY: 0.07,
  orbitSpeedZ: 0.1,
  orbitDirX: 1,
  orbitDirY: 1,
  orbitDirZ: 1,
  seesaw: false,
  seesawAxis: "x",
  seesawAmount: 14,
  seesawAmountX: 16,
  seesawAmountY: 0,
  seesawAmountZ: 0,
  seesawSpeed: 1.0,
  seesawDir: 1,
  seesawMode: "dual",
  animPivotX: 0,
  animPivotY: 0,
  animPivotZ: 0,
  float: true,
  stutter: 0,

  colorA: "#00E5FF",
  colorB: "#2E7BFF",
  colorC: "#8B5CF6",
  colorD: "#FF2BD6",
  colorE: "#FF7AB6",
  colorF: "#FFB020",
  glow: 1.28,
  iridescence: 1,
  fresnelPower: 2.6,
  metalness: 0.22,
  roughness: 0.18,
  clearcoat: 1,
  transmission: 0.12,
  animateColors: true,
  animateGlow: true,
  colorSpeed: 0.28,
  colorFlowDir: 1,
  streakOn: true,
  streakSpeed: 0.22,
  streakIntensity: 0.62,
  highlightAmount: 0.42,

  keyIntensity: 2.9,
  keyColor: "#7EC8FF",
  fillIntensity: 1.15,
  fillColor: "#FF8AD4",
  rimIntensity: 3.4,
  rimColor: "#FF7A45",
  ambientIntensity: 0.32,

  bloomIntensity: 1.9,
  bloomThreshold: 0.12,
  bloomSmoothing: 0.38,

  particlesOn: false,
  particleAmount: 48,
  particleSize: 1.05,
  particleBrightness: 0.4,
  particleSpeed: 0.16,
  particleSpread: 2.55,
  particleDrift: 0.2,
  particleOpacity: 0.22,

  ringsOn: false,
  ringCount: 2,
  ringRadius: 0.925,
  ringOpacity: 0.18,
  ringSpeed: 0.1,
  ringAxis: "y",
  ringDirection: 1,
  ringGlow: 0.55,

  audioResponse: 0.85,
  transitionDuration: 0.55,
};

const ATLAS_FLOW = {
  colorA: "#00E5FF",
  colorB: "#2E7BFF",
  colorC: "#8B5CF6",
  colorD: "#FF2BD6",
  colorE: "#FF7AB6",
  colorF: "#FFB020",
  animateColors: true,
  colorFlowDir: 1,
  streakOn: true,
  shapeType: "organic" as const,
  showTube: true,
};

function look(patch: Partial<SophiaSettings>): SophiaSettings {
  return { ...defaultSettings, ...patch };
}

export const STATE_PRESETS: SavedPreset[] = [
  {
    id: "state-idle",
    name: "01 Idle",
    builtin: true,
    role: "state",
    swatches: ["#00E5FF", "#8B5CF6", "#FF7AB6"],
    settings: look({
      ...ATLAS_FLOW,
      majorRadius: 0.6,
      tubeRadius: 0.17,
      organic: 0.12,
      asymmetry: 0,
      aperture: 0,
      knotness: 0,
      breathing: 0.042,
      stretch: 1,
      compress: 0,
      twist: 0,
      waveAmount: 0.02,
      waveSpeed: 0.55,
      bendX: 0,
      bendY: 0,
      bendZ: 0,
      taper: 0.08,
      noise: 0.028,
      orientX: 8,
      orientY: -6,
      orientZ: -3,
      speed: 0.32,
      float: true,
      stutter: 0,
      glow: 1.22,
      colorSpeed: 0.18,
      streakSpeed: 0.16,
      streakIntensity: 0.48,
      highlightAmount: 0.36,
      orbitX: false,
      orbitY: true,
      orbitZ: false,
      orbitSpeedY: 0.045,
      seesaw: false,
      particlesOn: false,
      ringsOn: false,
      attentionDot: false,
      warningAccent: false,
      audioResponse: 0.25,
      bloomIntensity: 1.7,
    }),
  },
  {
    id: "state-listening",
    name: "02 Listening",
    builtin: true,
    role: "state",
    swatches: ["#00E5FF", "#2E7BFF", "#FFB020"],
    settings: look({
      ...ATLAS_FLOW,
      majorRadius: 0.58,
      tubeRadius: 0.165,
      organic: 0.16,
      asymmetry: 0.46,
      aperture: 0.78,
      knotness: 0.04,
      bendX: 10,
      bendY: 4,
      bendZ: 22,
      orientX: 16,
      orientY: -26,
      orientZ: 8,
      pivotX: 0.12,
      speed: 0.52,
      breathing: 0.058,
      waveAmount: 0.07,
      waveAxis: "x",
      waveSpeed: 0.95,
      animateWave: true,
      stretch: 1.06,
      float: true,
      stutter: 0,
      glow: 1.46,
      colorSpeed: 0.32,
      streakSpeed: 0.42,
      streakIntensity: 0.78,
      highlightAmount: 0.58,
      orbitY: true,
      orbitSpeedY: 0.07,
      seesaw: false,
      particlesOn: false,
      ringsOn: true,
      ringCount: 3,
      ringRadius: 0.82,
      ringOpacity: 0.28,
      ringSpeed: 0.22,
      ringAxis: "y",
      ringGlow: 0.7,
      attentionDot: false,
      warningAccent: false,
      audioResponse: 1.2,
      bloomIntensity: 1.95,
    }),
  },
  {
    id: "state-working",
    name: "03 Working",
    builtin: true,
    role: "state",
    swatches: ["#00E5FF", "#8B5CF6", "#FF2BD6"],
    settings: look({
      ...ATLAS_FLOW,
      majorRadius: 0.56,
      tubeRadius: 0.145,
      organic: 0.22,
      asymmetry: 0.08,
      aperture: 0.06,
      knotness: 0.84,
      twist: 58,
      twistAxis: "y",
      animateTwist: true,
      waveAmount: 0.2,
      waveAxis: "x",
      waveSpeed: 1.65,
      animateWave: true,
      revolve: 0.35,
      noise: 0.055,
      noiseScale: 2.1,
      animateNoise: true,
      speed: 0.92,
      float: true,
      stutter: 0,
      orbitY: true,
      orbitSpeedY: 0.18,
      glow: 1.62,
      bloomIntensity: 2.25,
      colorSpeed: 0.55,
      streakSpeed: 0.88,
      streakIntensity: 1.12,
      highlightAmount: 0.82,
      seesaw: false,
      particlesOn: true,
      particleAmount: 72,
      particleSize: 1.05,
      particleBrightness: 0.55,
      particleSpeed: 0.42,
      particleSpread: 2.4,
      particleDrift: 0.32,
      particleOpacity: 0.38,
      ringsOn: false,
      attentionDot: false,
      warningAccent: false,
      audioResponse: 0.4,
    }),
  },
  {
    id: "state-speaking",
    name: "04 Speaking",
    builtin: true,
    role: "state",
    swatches: ["#2E7BFF", "#FF2BD6", "#FF7AB6"],
    settings: look({
      ...ATLAS_FLOW,
      majorRadius: 0.57,
      tubeRadius: 0.15,
      organic: 0.15,
      knotness: 0.38,
      aperture: 0.12,
      asymmetry: 0.06,
      stretch: 1.52,
      stretchAxis: "x",
      compress: 0.18,
      waveAmount: 0.24,
      waveAxis: "x",
      waveSpeed: 1.7,
      animateWave: true,
      speed: 0.95,
      glow: 1.72,
      bloomIntensity: 2.15,
      colorSpeed: 0.44,
      streakSpeed: 0.7,
      streakIntensity: 0.95,
      highlightAmount: 0.88,
      seesaw: true,
      seesawAxis: "x",
      seesawAmountX: 12,
      seesawAmountY: 6,
      seesawSpeed: 1.25,
      seesawMode: "dual",
      float: true,
      stutter: 0,
      orbitY: false,
      particlesOn: false,
      ringsOn: true,
      ringCount: 3,
      ringRadius: 1.05,
      ringOpacity: 0.24,
      ringSpeed: 0.32,
      ringGlow: 0.8,
      attentionDot: false,
      warningAccent: false,
      audioResponse: 1.65,
    }),
  },
  {
    id: "state-needs-you",
    name: "05 Needs You",
    builtin: true,
    role: "state",
    swatches: ["#2E7BFF", "#8B5CF6", "#FF2BD6"],
    settings: look({
      ...ATLAS_FLOW,
      majorRadius: 0.58,
      tubeRadius: 0.16,
      organic: 0.14,
      orientX: 30,
      orientY: -14,
      orientZ: 4,
      asymmetry: 0.4,
      aperture: 0.58,
      knotness: 0.08,
      taper: 0.36,
      taperAxis: "x",
      stretch: 1.14,
      speed: 0.22,
      breathing: 0.048,
      float: false,
      stutter: 0,
      attentionDot: true,
      warningAccent: false,
      glow: 1.4,
      colorSpeed: 0.16,
      streakSpeed: 0.18,
      streakIntensity: 0.5,
      highlightAmount: 0.55,
      orbitY: false,
      seesaw: false,
      particlesOn: false,
      ringsOn: false,
      audioResponse: 0.35,
      bloomIntensity: 1.85,
    }),
  },
  {
    id: "state-paused",
    name: "06 Paused",
    builtin: true,
    role: "state",
    swatches: ["#2E7BFF", "#8B5CF6", "#FFB020"],
    settings: look({
      ...ATLAS_FLOW,
      majorRadius: 0.62,
      tubeRadius: 0.155,
      organic: 0.1,
      knotness: 0.05,
      aperture: 0.1,
      asymmetry: 0.04,
      compress: 0.5,
      stretch: 1.28,
      stretchAxis: "x",
      bendX: -72,
      bendY: 0,
      bendZ: 8,
      taper: 0.22,
      orientX: 58,
      orientY: 0,
      orientZ: 0,
      speed: 0.05,
      breathing: 0.01,
      glow: 0.74,
      bloomIntensity: 1.15,
      colorSpeed: 0.06,
      streakSpeed: 0.06,
      streakIntensity: 0.18,
      highlightAmount: 0.14,
      float: false,
      stutter: 0,
      orbitX: false,
      orbitY: false,
      orbitZ: false,
      seesaw: false,
      animateWave: false,
      waveAmount: 0,
      particlesOn: false,
      ringsOn: false,
      attentionDot: false,
      warningAccent: false,
      audioResponse: 0,
    }),
  },
  {
    id: "state-blocked",
    name: "07 Blocked",
    builtin: true,
    role: "state",
    swatches: ["#2E7BFF", "#8B5CF6", "#FFB020"],
    settings: look({
      ...ATLAS_FLOW,
      majorRadius: 0.57,
      tubeRadius: 0.15,
      organic: 0.18,
      knotness: 0.28,
      aperture: -0.68,
      taper: -0.42,
      taperAxis: "x",
      twist: 48,
      twistAxis: "y",
      compress: 0.36,
      noise: 0.09,
      noiseScale: 2.5,
      animateNoise: true,
      speed: 0.42,
      stutter: 0.72,
      glow: 1.42,
      bloomIntensity: 2.05,
      colorSpeed: 0.2,
      streakSpeed: 0.14,
      streakIntensity: 0.52,
      highlightAmount: 0.4,
      seesaw: true,
      seesawAmountX: 16,
      seesawAmountZ: 8,
      seesawSpeed: 2.35,
      seesawMode: "dual",
      float: false,
      orbitY: false,
      particlesOn: false,
      ringsOn: false,
      attentionDot: false,
      warningAccent: true,
      audioResponse: 0.15,
    }),
  },
  {
    id: "state-completed",
    name: "08 Completed",
    builtin: true,
    role: "state",
    swatches: ["#00E5FF", "#FF2BD6", "#FFB020"],
    settings: look({
      ...ATLAS_FLOW,
      majorRadius: 0.6,
      tubeRadius: 0.18,
      organic: 0.1,
      asymmetry: 0,
      aperture: 0,
      knotness: 0,
      breathing: 0.018,
      stretch: 1,
      compress: 0,
      twist: 0,
      waveAmount: 0.04,
      speed: 0.28,
      glow: 2.35,
      bloomIntensity: 2.8,
      highlightAmount: 1.32,
      colorSpeed: 0.34,
      streakSpeed: 0.48,
      streakIntensity: 1.08,
      float: true,
      stutter: 0,
      orbitY: true,
      orbitSpeedY: 0.035,
      seesaw: false,
      particlesOn: true,
      particleAmount: 36,
      particleSize: 1.2,
      particleBrightness: 0.7,
      particleSpeed: 0.12,
      particleSpread: 1.85,
      particleOpacity: 0.42,
      ringsOn: false,
      attentionDot: false,
      warningAccent: false,
      audioResponse: 0.2,
    }),
  },
  {
    id: "state-understanding",
    name: "Understanding (Atlas Working)",
    builtin: true,
    role: "state",
    swatches: ["#00E5FF", "#8B5CF6", "#FF2BD6"],
    settings: look({
      ...ATLAS_FLOW,
      majorRadius: 0.56,
      tubeRadius: 0.145,
      organic: 0.22,
      knotness: 0.84,
      twist: 58,
      waveAmount: 0.2,
      waveSpeed: 1.65,
      animateWave: true,
      speed: 0.92,
      glow: 1.62,
      particlesOn: true,
      particleAmount: 72,
      streakSpeed: 0.88,
      streakIntensity: 1.12,
    }),
  },
  {
    id: "state-waiting",
    name: "Waiting (Atlas Needs You)",
    builtin: true,
    role: "state",
    swatches: ["#2E7BFF", "#8B5CF6", "#FF2BD6"],
    settings: look({
      ...ATLAS_FLOW,
      majorRadius: 0.58,
      tubeRadius: 0.16,
      orientX: 30,
      orientY: -14,
      asymmetry: 0.4,
      aperture: 0.58,
      attentionDot: true,
      speed: 0.22,
      glow: 1.4,
      float: false,
      orbitY: false,
    }),
  },
];

export const SHAPE_PRESETS: SavedPreset[] = [
  {
    id: "sophia",
    name: "Sophia",
    builtin: true,
    role: "look",
    swatches: ["#2E7BFF", "#9B4DFF", "#FF4DAD"],
    settings: look({}),
  },
  {
    id: "siri",
    name: "Siri Orb",
    builtin: true,
    role: "look",
    swatches: ["#60A5FA", "#C4B5FD", "#F9A8D4"],
    settings: look({
      shapeType: "blob",
      majorRadius: 0.61,
      organic: 0.22,
      noise: 0.12,
      noiseScale: 1.2,
      glow: 1.55,
      colorA: "#5AB0FF",
      colorB: "#B794FF",
      colorC: "#FF9AD4",
      colorD: "#FFE0A3",
      orbitSpeedY: 0.16,
      transmission: 0.22,
    }),
  },
  {
    id: "deepgram",
    name: "Deepgram",
    builtin: true,
    role: "look",
    swatches: ["#22D3EE", "#6366F1", "#34D399"],
    settings: look({
      organic: 0.06,
      tubeRadius: 0.15,
      colorA: "#22D3EE",
      colorB: "#6366F1",
      colorC: "#818CF8",
      colorD: "#34D399",
      glow: 1.5,
      keyColor: "#67E8F9",
      rimColor: "#4ADE80",
      fillColor: "#A5B4FC",
    }),
  },
  {
    id: "noise-flow",
    name: "Noise Flow",
    builtin: true,
    role: "look",
    swatches: ["#38BDF8", "#A78BFA", "#F472B6"],
    settings: look({
      shapeType: "organic",
      noise: 0.28,
      noiseScale: 2.4,
      organic: 0.22,
      glow: 1.6,
      colorSpeed: 0.55,
      speed: 0.8,
    }),
  },
  {
    id: "twisted",
    name: "Twisted Ribbon",
    builtin: true,
    role: "look",
    swatches: ["#818CF8", "#E879F9", "#FB7185"],
    settings: look({
      shapeType: "organic",
      tubeRadius: 0.11,
      twist: 420,
      twistAxis: "y",
      animateTwist: true,
      organic: 0.16,
      glow: 1.35,
      colorA: "#818CF8",
      colorB: "#C084FC",
      colorC: "#E879F9",
      colorD: "#FB7185",
    }),
  },
  {
    id: "plasma-knot",
    name: "Plasma Knot",
    builtin: true,
    role: "look",
    swatches: ["#22D3EE", "#A855F7", "#FB7185"],
    settings: look({
      shapeType: "knot",
      p: 3,
      q: 2,
      majorRadius: 0.525,
      tubeRadius: 0.14,
      noise: 0.05,
      glow: 1.7,
      orbitX: true,
      orbitSpeedX: 0.08,
      colorA: "#22D3EE",
      colorB: "#818CF8",
      colorC: "#D946EF",
      colorD: "#FB7185",
    }),
  },
  {
    id: "aurora",
    name: "Aurora",
    builtin: true,
    role: "look",
    swatches: ["#34D399", "#22D3EE", "#A78BFA"],
    settings: look({
      organic: 0.18,
      colorSpeed: 0.7,
      glow: 1.65,
      colorA: "#34D399",
      colorB: "#22D3EE",
      colorC: "#818CF8",
      colorD: "#C084FC",
      keyColor: "#6EE7B7",
      rimColor: "#A78BFA",
      speed: 0.4,
    }),
  },
  {
    id: "inferno",
    name: "Inferno",
    builtin: true,
    role: "look",
    swatches: ["#F97316", "#EF4444", "#FBBF24"],
    settings: look({
      shapeType: "organic",
      organic: 0.14,
      noise: 0.1,
      glow: 1.8,
      colorA: "#FBBF24",
      colorB: "#F97316",
      colorC: "#EF4444",
      colorD: "#9F1239",
      keyColor: "#FDBA74",
      fillColor: "#FB7185",
      rimColor: "#F59E0B",
      bloomIntensity: 2.1,
    }),
  },
  {
    id: "ice",
    name: "Ice Crystal",
    builtin: true,
    role: "look",
    swatches: ["#E0F2FE", "#38BDF8", "#818CF8"],
    settings: look({
      tubeRadius: 0.15,
      organic: 0.04,
      noise: 0.02,
      metalness: 0.55,
      roughness: 0.08,
      transmission: 0.28,
      glow: 1.2,
      colorA: "#E0F2FE",
      colorB: "#7DD3FC",
      colorC: "#38BDF8",
      colorD: "#818CF8",
      keyColor: "#E0F2FE",
      fillColor: "#93C5FD",
      rimColor: "#A5B4FC",
      animateColors: false,
    }),
  },
  {
    id: "seesaw",
    name: "See-Saw",
    builtin: true,
    role: "look",
    swatches: ["#60A5FA", "#A78BFA", "#F472B6"],
    settings: look({
      seesaw: true,
      seesawAxis: "x",
      seesawAmount: 42,
      orbitY: false,
      animateBend: true,
      bend: 35,
      bendAxis: "z",
      speed: 0.7,
    }),
  },
  {
    id: "bend-wave",
    name: "Bend Wave",
    builtin: true,
    role: "look",
    swatches: ["#818CF8", "#F472B6", "#FB923C"],
    settings: look({
      animateBend: true,
      bend: 150,
      bendAxis: "z",
      speed: 0.45,
      orbitY: true,
      orbitSpeedY: 0.06,
      glow: 1.5,
    }),
  },
  {
    id: "liquid",
    name: "Liquid Glass",
    builtin: true,
    role: "look",
    swatches: ["#67E8F9", "#C4B5FD", "#F9A8D4"],
    settings: look({
      shapeType: "organic",
      organic: 0.2,
      noise: 0.08,
      transmission: 0.42,
      roughness: 0.08,
      metalness: 0.05,
      glow: 1.25,
      colorA: "#67E8F9",
      colorB: "#A5B4FC",
      colorC: "#F0ABFC",
      colorD: "#F9A8D4",
    }),
  },
];

export const BUILTIN_PRESETS: SavedPreset[] = [...STATE_PRESETS, ...SHAPE_PRESETS];

export const DEFAULT_ASSIGNMENTS: StateAssignments = {
  idle: "state-idle",
  listening: "state-listening",
  working: "state-working",
  speaking: "state-speaking",
  needs_you: "state-needs-you",
  paused: "state-paused",
  blocked: "state-blocked",
  completed: "state-completed",
  understanding: "state-working",
  waiting: "state-needs-you",
};

export function pickSettings(source: Record<string, unknown> | SophiaSettings): SophiaSettings {
  const out = { ...defaultSettings };
  (Object.keys(defaultSettings) as (keyof SophiaSettings)[]).forEach((key) => {
    const value = (source as SophiaSettings)[key];
    if (value !== undefined) {
      (out as unknown as Record<string, unknown>)[key as string] = value as unknown;
    }
  });
  return out;
}

export function normalizeSettings(partial: Partial<SophiaSettings> | undefined): SophiaSettings {
  return pickSettings({ ...defaultSettings, ...(partial ?? {}) });
}

export function factoryPreset(id: string): SavedPreset | undefined {
  const normalizedId = id === "state-needs_you" ? "state-needs-you" : id;
  const found = BUILTIN_PRESETS.find((p) => p.id === normalizedId || p.id === id);
  if (!found) return undefined;
  return { ...found, settings: pickSettings(found.settings) };
}

export const SETTING_KEYS = Object.keys(defaultSettings) as (keyof SophiaSettings)[];

export function isSettingsKey(key: string): key is keyof SophiaSettings {
  return key in defaultSettings;
}

export const STATE_LABELS: Record<VoiceState, string> = {
  idle: "01 Idle",
  listening: "02 Listening",
  working: "03 Working",
  speaking: "04 Speaking",
  needs_you: "05 Needs You",
  paused: "06 Paused",
  blocked: "07 Blocked",
  completed: "08 Completed",
  understanding: "Working",
  waiting: "Needs You",
};
