import type { SavedPreset, SophiaSettings, StateAssignments, VoiceState } from "./types";

export const defaultSettings: SophiaSettings = {
  shapeType: "torus",
  majorRadius: 0.58,
  tubeRadius: 0.178,
  showTube: true,
  p: 2,
  q: 3,
  organic: 0.13,
  asymmetry: 0,
  aperture: 0,
  breathing: 0.035,
  attentionDot: false,

  pivotX: 0,
  pivotY: 0,
  pivotZ: 0,

  bend: 0,
  bendAxis: "z",
  bendX: 0,
  bendY: 0,
  bendZ: 0,
  animateBend: false,
  taper: 0.12,
  taperAxis: "x",
  animateTaper: false,
  stretch: 1,
  stretchAxis: "x",
  compress: 0,
  twist: 0,
  twistAxis: "y",
  animateTwist: false,
  waveAmount: 0,
  waveAxis: "x",
  waveSpeed: 0.8,
  animateWave: true,
  noise: 0.035,
  noiseScale: 1.6,
  animateNoise: true,
  revolve: 0,

  orientX: 12,
  orientY: -8,
  orientZ: -5,
  speed: 0.45,
  orbitX: false,
  orbitY: true,
  orbitZ: false,
  orbitSpeedX: 0.12,
  orbitSpeedY: 0.07,
  orbitSpeedZ: 0.1,
  orbitDirX: 1,
  orbitDirY: 1,
  orbitDirZ: 1,
  seesaw: false,
  seesawAxis: "x",
  seesawAmount: 14,
  seesawAmountX: 16,
  seesawAmountY: 0,
  seesawAmountZ: 0,
  seesawSpeed: 1.0,
  seesawDir: 1,
  seesawMode: "dual",
  animPivotX: 0,
  animPivotY: 0,
  animPivotZ: 0,
  float: true,

  colorA: "#2E7BFF",
  colorB: "#9B4DFF",
  colorC: "#FF4DAD",
  colorD: "#FF5A3C",
  glow: 1.28,
  iridescence: 1,
  fresnelPower: 2.6,
  metalness: 0.22,
  roughness: 0.18,
  clearcoat: 1,
  transmission: 0.12,
  animateColors: true,
  animateGlow: true,
  colorSpeed: 0.28,
  colorFlowDir: 1,
  streakOn: true,
  streakSpeed: 0.22,
  streakIntensity: 0.62,
  highlightAmount: 0.42,

  keyIntensity: 2.9,
  keyColor: "#7EC8FF",
  fillIntensity: 1.15,
  fillColor: "#FF8AD4",
  rimIntensity: 3.4,
  rimColor: "#FF7A45",
  ambientIntensity: 0.32,

  bloomIntensity: 1.9,
  bloomThreshold: 0.12,
  bloomSmoothing: 0.38,

  particlesOn: false,
  particleAmount: 48,
  particleSize: 1.05,
  particleBrightness: 0.4,
  particleSpeed: 0.16,
  particleSpread: 2.55,
  particleDrift: 0.2,
  particleOpacity: 0.22,

  ringsOn: false,
  ringCount: 2,
  ringRadius: 0.925,
  ringOpacity: 0.18,
  ringSpeed: 0.1,
  ringAxis: "y",
  ringDirection: 1,
  ringGlow: 0.55,
};

function look(patch: Partial<SophiaSettings>): SophiaSettings {
  return { ...defaultSettings, ...patch };
}

export const STATE_PRESETS: SavedPreset[] = [
  {
    id: "state-idle",
    name: "01 Idle",
    builtin: true,
    role: "state",
    swatches: ["#00c6ff", "#7b2cbf", "#ec4899"],
    settings: look({
      shapeType: "organic",
      majorRadius: 0.6,
      tubeRadius: 0.17,
      organic: 0.14,
      asymmetry: 0,
      aperture: 0,
      breathing: 0.038,
      stretch: 1.0,
      compress: 0,
      bendX: 0,
      bendY: 0,
      bendZ: 0,
      orientX: 8,
      orientY: -6,
      orientZ: -3,
      speed: 0.38,
      float: true,
      glow: 1.24,
      colorA: "#00c6ff",
      colorB: "#7b2cbf",
      colorC: "#ec4899",
      colorD: "#f97316",
      colorSpeed: 0.24,
      streakOn: true,
      streakSpeed: 0.22,
      streakIntensity: 0.58,
      highlightAmount: 0.38,
      orbitX: false,
      orbitY: true,
      orbitSpeedY: 0.06,
      seesaw: false,
      particlesOn: false,
      ringsOn: false,
    }),
  },
  {
    id: "state-listening",
    name: "02 Listening",
    builtin: true,
    role: "state",
    swatches: ["#06b6d4", "#3b82f6", "#f97316"],
    settings: look({
      shapeType: "organic",
      majorRadius: 0.58,
      tubeRadius: 0.165,
      organic: 0.18,
      asymmetry: 0.48,
      aperture: 0.2,
      bendX: 18,
      bendZ: 28,
      orientX: 16,
      orientY: -22,
      orientZ: 8,
      speed: 0.58,
      breathing: 0.055,
      float: true,
      glow: 1.48,
      colorA: "#06b6d4",
      colorB: "#3b82f6",
      colorC: "#ec4899",
      colorD: "#f97316",
      colorSpeed: 0.36,
      streakOn: true,
      streakSpeed: 0.48,
      streakIntensity: 0.82,
      highlightAmount: 0.62,
      orbitY: true,
      orbitSpeedY: 0.09,
      seesaw: false,
      particlesOn: false,
      ringsOn: false,
    }),
  },
  {
    id: "state-working",
    name: "03 Working",
    builtin: true,
    role: "state",
    swatches: ["#38bdf8", "#818cf8", "#f43f5e"],
    settings: look({
      shapeType: "knot",
      p: 2,
      q: 3,
      majorRadius: 0.54,
      tubeRadius: 0.115,
      twist: 38,
      waveAmount: 0.16,
      waveAxis: "x",
      waveSpeed: 1.5,
      animateWave: true,
      speed: 0.88,
      float: true,
      orbitY: true,
      orbitSpeedY: 0.16,
      glow: 1.58,
      bloomIntensity: 2.2,
      colorA: "#38bdf8",
      colorB: "#818cf8",
      colorC: "#f43f5e",
      colorD: "#fb923c",
      colorSpeed: 0.45,
      streakOn: true,
      streakSpeed: 0.72,
      streakIntensity: 0.96,
      highlightAmount: 0.75,
      seesaw: false,
      particlesOn: false,
      ringsOn: false,
    }),
  },
  {
    id: "state-speaking",
    name: "04 Speaking",
    builtin: true,
    role: "state",
    swatches: ["#38bdf8", "#c084fc", "#f43f5e"],
    settings: look({
      shapeType: "organic",
      majorRadius: 0.56,
      tubeRadius: 0.145,
      stretch: 1.58,
      stretchAxis: "x",
      compress: 0.22,
      waveAmount: 0.22,
      waveAxis: "x",
      waveSpeed: 1.55,
      animateWave: true,
      speed: 0.95,
      glow: 1.68,
      bloomIntensity: 2.1,
      colorA: "#38bdf8",
      colorB: "#c084fc",
      colorC: "#f43f5e",
      colorD: "#fb7185",
      colorSpeed: 0.42,
      streakOn: true,
      streakSpeed: 0.65,
      streakIntensity: 0.88,
      highlightAmount: 0.82,
      seesaw: true,
      seesawAxis: "x",
      seesawAmountX: 14,
      seesawSpeed: 1.3,
      seesawMode: "dual",
      float: true,
      particlesOn: false,
      ringsOn: false,
    }),
  },
  {
    id: "state-needs-you",
    name: "05 Needs You",
    builtin: true,
    role: "state",
    swatches: ["#0284c7", "#6366f1", "#f43f5e"],
    settings: look({
      shapeType: "organic",
      majorRadius: 0.58,
      tubeRadius: 0.16,
      orientX: 28,
      orientY: -14,
      orientZ: 4,
      asymmetry: 0.38,
      taper: 0.32,
      taperAxis: "x",
      stretch: 1.14,
      speed: 0.24,
      breathing: 0.045,
      float: false,
      attentionDot: true,
      glow: 1.38,
      colorA: "#0284c7",
      colorB: "#6366f1",
      colorC: "#f43f5e",
      colorD: "#f59e0b",
      colorSpeed: 0.22,
      streakOn: true,
      streakSpeed: 0.2,
      streakIntensity: 0.52,
      highlightAmount: 0.55,
      orbitY: false,
      seesaw: false,
      particlesOn: false,
      ringsOn: false,
    }),
  },
  {
    id: "state-paused",
    name: "06 Paused",
    builtin: true,
    role: "state",
    swatches: ["#1e3a8a", "#4338ca", "#ea580c"],
    settings: look({
      shapeType: "torus",
      majorRadius: 0.65,
      tubeRadius: 0.125,
      compress: 0.52,
      stretch: 1.25,
      stretchAxis: "x",
      bendX: -65,
      orientX: 62,
      orientY: 0,
      orientZ: 0,
      speed: 0.06,
      glow: 0.78,
      bloomIntensity: 1.2,
      colorA: "#1e3a8a",
      colorB: "#4338ca",
      colorC: "#b91c1c",
      colorD: "#ea580c",
      colorSpeed: 0.08,
      streakOn: true,
      streakSpeed: 0.08,
      streakIntensity: 0.2,
      highlightAmount: 0.16,
      float: false,
      orbitY: false,
      seesaw: false,
      particlesOn: false,
      ringsOn: false,
    }),
  },
  {
    id: "state-blocked",
    name: "07 Blocked",
    builtin: true,
    role: "state",
    swatches: ["#0284c7", "#7c3aed", "#e11d48"],
    settings: look({
      shapeType: "organic",
      majorRadius: 0.58,
      tubeRadius: 0.155,
      aperture: -0.42,
      taper: -0.48,
      taperAxis: "x",
      twist: 52,
      compress: 0.34,
      noise: 0.085,
      noiseScale: 2.4,
      speed: 0.45,
      glow: 1.45,
      bloomIntensity: 2.0,
      colorA: "#0284c7",
      colorB: "#7c3aed",
      colorC: "#e11d48",
      colorD: "#f97316",
      colorSpeed: 0.25,
      streakOn: true,
      streakSpeed: 0.18,
      streakIntensity: 0.55,
      highlightAmount: 0.42,
      seesaw: true,
      seesawAmountX: 18,
      seesawSpeed: 2.2,
      seesawMode: "dual",
      float: false,
      orbitY: false,
      particlesOn: false,
      ringsOn: false,
    }),
  },
  {
    id: "state-completed",
    name: "08 Completed",
    builtin: true,
    role: "state",
    swatches: ["#38bdf8", "#a855f7", "#fbbf24"],
    settings: look({
      shapeType: "organic",
      majorRadius: 0.6,
      tubeRadius: 0.18,
      asymmetry: 0,
      aperture: 0,
      breathing: 0.02,
      speed: 0.32,
      glow: 2.25,
      bloomIntensity: 2.75,
      highlightAmount: 1.25,
      colorA: "#38bdf8",
      colorB: "#a855f7",
      colorC: "#f43f5e",
      colorD: "#fbbf24",
      colorSpeed: 0.3,
      streakOn: true,
      streakSpeed: 0.42,
      streakIntensity: 0.95,
      float: true,
      orbitY: true,
      orbitSpeedY: 0.04,
      seesaw: false,
      particlesOn: false,
      ringsOn: false,
    }),
  },
  {
    id: "state-understanding",
    name: "Understanding (Atlas Working)",
    builtin: true,
    role: "state",
    swatches: ["#38bdf8", "#818cf8", "#f43f5e"],
    settings: look({
      shapeType: "knot",
      p: 2,
      q: 3,
      majorRadius: 0.54,
      tubeRadius: 0.115,
      twist: 38,
      speed: 0.88,
      glow: 1.58,
    }),
  },
  {
    id: "state-waiting",
    name: "Waiting (Atlas Needs You)",
    builtin: true,
    role: "state",
    swatches: ["#0284c7", "#6366f1", "#f43f5e"],
    settings: look({
      shapeType: "organic",
      majorRadius: 0.58,
      tubeRadius: 0.16,
      orientX: 28,
      orientY: -14,
      asymmetry: 0.38,
      attentionDot: true,
      speed: 0.24,
      glow: 1.38,
    }),
  },
];

export const SHAPE_PRESETS: SavedPreset[] = [
  {
    id: "sophia",
    name: "Sophia",
    builtin: true,
    role: "look",
    swatches: ["#2E7BFF", "#9B4DFF", "#FF4DAD"],
    settings: look({}),
  },
  {
    id: "siri",
    name: "Siri Orb",
    builtin: true,
    role: "look",
    swatches: ["#60A5FA", "#C4B5FD", "#F9A8D4"],
    settings: look({
      shapeType: "blob",
      majorRadius: 0.61,
      organic: 0.22,
      noise: 0.12,
      noiseScale: 1.2,
      glow: 1.55,
      colorA: "#5AB0FF",
      colorB: "#B794FF",
      colorC: "#FF9AD4",
      colorD: "#FFE0A3",
      orbitSpeedY: 0.16,
      transmission: 0.22,
    }),
  },
  {
    id: "deepgram",
    name: "Deepgram",
    builtin: true,
    role: "look",
    swatches: ["#22D3EE", "#6366F1", "#34D399"],
    settings: look({
      organic: 0.06,
      tubeRadius: 0.15,
      colorA: "#22D3EE",
      colorB: "#6366F1",
      colorC: "#818CF8",
      colorD: "#34D399",
      glow: 1.5,
      keyColor: "#67E8F9",
      rimColor: "#4ADE80",
      fillColor: "#A5B4FC",
    }),
  },
  {
    id: "noise-flow",
    name: "Noise Flow",
    builtin: true,
    role: "look",
    swatches: ["#38BDF8", "#A78BFA", "#F472B6"],
    settings: look({
      shapeType: "organic",
      noise: 0.28,
      noiseScale: 2.4,
      organic: 0.22,
      glow: 1.6,
      colorSpeed: 0.55,
      speed: 0.8,
    }),
  },
  {
    id: "twisted",
    name: "Twisted Ribbon",
    builtin: true,
    role: "look",
    swatches: ["#818CF8", "#E879F9", "#FB7185"],
    settings: look({
      shapeType: "organic",
      tubeRadius: 0.11,
      twist: 420,
      twistAxis: "y",
      animateTwist: true,
      organic: 0.16,
      glow: 1.35,
      colorA: "#818CF8",
      colorB: "#C084FC",
      colorC: "#E879F9",
      colorD: "#FB7185",
    }),
  },
  {
    id: "plasma-knot",
    name: "Plasma Knot",
    builtin: true,
    role: "look",
    swatches: ["#22D3EE", "#A855F7", "#FB7185"],
    settings: look({
      shapeType: "knot",
      p: 3,
      q: 2,
      majorRadius: 0.525,
      tubeRadius: 0.14,
      noise: 0.05,
      glow: 1.7,
      orbitX: true,
      orbitSpeedX: 0.08,
      colorA: "#22D3EE",
      colorB: "#818CF8",
      colorC: "#D946EF",
      colorD: "#FB7185",
    }),
  },
  {
    id: "aurora",
    name: "Aurora",
    builtin: true,
    role: "look",
    swatches: ["#34D399", "#22D3EE", "#A78BFA"],
    settings: look({
      organic: 0.18,
      colorSpeed: 0.7,
      glow: 1.65,
      colorA: "#34D399",
      colorB: "#22D3EE",
      colorC: "#818CF8",
      colorD: "#C084FC",
      keyColor: "#6EE7B7",
      rimColor: "#A78BFA",
      speed: 0.4,
    }),
  },
  {
    id: "inferno",
    name: "Inferno",
    builtin: true,
    role: "look",
    swatches: ["#F97316", "#EF4444", "#FBBF24"],
    settings: look({
      shapeType: "organic",
      organic: 0.14,
      noise: 0.1,
      glow: 1.8,
      colorA: "#FBBF24",
      colorB: "#F97316",
      colorC: "#EF4444",
      colorD: "#9F1239",
      keyColor: "#FDBA74",
      fillColor: "#FB7185",
      rimColor: "#F59E0B",
      bloomIntensity: 2.1,
    }),
  },
  {
    id: "ice",
    name: "Ice Crystal",
    builtin: true,
    role: "look",
    swatches: ["#E0F2FE", "#38BDF8", "#818CF8"],
    settings: look({
      tubeRadius: 0.15,
      organic: 0.04,
      noise: 0.02,
      metalness: 0.55,
      roughness: 0.08,
      transmission: 0.28,
      glow: 1.2,
      colorA: "#E0F2FE",
      colorB: "#7DD3FC",
      colorC: "#38BDF8",
      colorD: "#818CF8",
      keyColor: "#E0F2FE",
      fillColor: "#93C5FD",
      rimColor: "#A5B4FC",
      animateColors: false,
    }),
  },
  {
    id: "seesaw",
    name: "See-Saw",
    builtin: true,
    role: "look",
    swatches: ["#60A5FA", "#A78BFA", "#F472B6"],
    settings: look({
      seesaw: true,
      seesawAxis: "x",
      seesawAmount: 42,
      orbitY: false,
      animateBend: true,
      bend: 35,
      bendAxis: "z",
      speed: 0.7,
    }),
  },
  {
    id: "bend-wave",
    name: "Bend Wave",
    builtin: true,
    role: "look",
    swatches: ["#818CF8", "#F472B6", "#FB923C"],
    settings: look({
      animateBend: true,
      bend: 150,
      bendAxis: "z",
      speed: 0.45,
      orbitY: true,
      orbitSpeedY: 0.06,
      glow: 1.5,
    }),
  },
  {
    id: "liquid",
    name: "Liquid Glass",
    builtin: true,
    role: "look",
    swatches: ["#67E8F9", "#C4B5FD", "#F9A8D4"],
    settings: look({
      shapeType: "organic",
      organic: 0.2,
      noise: 0.08,
      transmission: 0.42,
      roughness: 0.08,
      metalness: 0.05,
      glow: 1.25,
      colorA: "#67E8F9",
      colorB: "#A5B4FC",
      colorC: "#F0ABFC",
      colorD: "#F9A8D4",
    }),
  },
];

export const BUILTIN_PRESETS: SavedPreset[] = [...STATE_PRESETS, ...SHAPE_PRESETS];

export const DEFAULT_ASSIGNMENTS: StateAssignments = {
  idle: "state-idle",
  listening: "state-listening",
  working: "state-working",
  speaking: "state-speaking",
  needs_you: "state-needs-you",
  paused: "state-paused",
  blocked: "state-blocked",
  completed: "state-completed",
  understanding: "state-working",
  waiting: "state-needs-you",
};

export function pickSettings(source: Record<string, unknown> | SophiaSettings): SophiaSettings {
  const out = { ...defaultSettings };
  (Object.keys(defaultSettings) as (keyof SophiaSettings)[]).forEach((key) => {
    const value = (source as SophiaSettings)[key];
    if (value !== undefined) {
      (out as unknown as Record<string, unknown>)[key as string] = value as unknown;
    }
  });
  return out;
}

export function normalizeSettings(partial: Partial<SophiaSettings> | undefined): SophiaSettings {
  return pickSettings({ ...defaultSettings, ...(partial ?? {}) });
}

export function factoryPreset(id: string): SavedPreset | undefined {
  const normalizedId = id === "state-needs_you" ? "state-needs-you" : id;
  const found = BUILTIN_PRESETS.find((p) => p.id === normalizedId || p.id === id);
  if (!found) return undefined;
  return { ...found, settings: pickSettings(found.settings) };
}

export const SETTING_KEYS = Object.keys(defaultSettings) as (keyof SophiaSettings)[];

export function isSettingsKey(key: string): key is keyof SophiaSettings {
  return key in defaultSettings;
}

export const STATE_LABELS: Record<VoiceState, string> = {
  idle: "01 Idle",
  listening: "02 Listening",
  working: "03 Working",
  speaking: "04 Speaking",
  needs_you: "05 Needs You",
  paused: "06 Paused",
  blocked: "07 Blocked",
  completed: "08 Completed",
  understanding: "Working",
  waiting: "Needs You",
};
