import type { SophiaSettings, SavedPreset } from "./types";

export const defaultSettings: SophiaSettings = {
  shapeType: "torus",
  majorRadius: 1.16,
  tubeRadius: 0.355,
  p: 2,
  q: 3,
  organic: 0.13,

  bend: 0,
  bendAxis: "z",
  animateBend: false,
  taper: 0.12,
  taperAxis: "x",
  animateTaper: false,
  twist: 0,
  twistAxis: "y",
  animateTwist: false,
  noise: 0.035,
  noiseScale: 1.6,
  animateNoise: true,
  revolve: 0,

  speed: 0.55,
  orbitX: false,
  orbitY: true,
  orbitZ: false,
  orbitSpeedX: 0.18,
  orbitSpeedY: 0.1,
  orbitSpeedZ: 0.14,
  seesaw: false,
  seesawAxis: "x",
  seesawAmount: 28,
  float: true,

  colorA: "#2E7BFF",
  colorB: "#9B4DFF",
  colorC: "#FF4DAD",
  colorD: "#FF5A3C",
  glow: 1.42,
  iridescence: 1,
  fresnelPower: 2.6,
  metalness: 0.22,
  roughness: 0.18,
  clearcoat: 1,
  transmission: 0.12,
  animateColors: true,
  animateGlow: true,
  colorSpeed: 0.32,

  keyIntensity: 2.9,
  keyColor: "#7EC8FF",
  fillIntensity: 1.15,
  fillColor: "#FF8AD4",
  rimIntensity: 3.4,
  rimColor: "#FF7A45",
  ambientIntensity: 0.32,

  bloomIntensity: 1.9,
  bloomThreshold: 0.12,
  bloomSmoothing: 0.38,
};

export const BUILTIN_PRESETS: SavedPreset[] = [
  {
    id: "sophia",
    name: "Sophia",
    builtin: true,
    swatches: ["#2E7BFF", "#9B4DFF", "#FF4DAD"],
    settings: { ...defaultSettings },
  },
  {
    id: "siri",
    name: "Siri Orb",
    builtin: true,
    swatches: ["#60A5FA", "#C4B5FD", "#F9A8D4"],
    settings: {
      ...defaultSettings,
      shapeType: "blob",
      majorRadius: 1.22,
      organic: 0.22,
      noise: 0.12,
      noiseScale: 1.2,
      animateNoise: true,
      glow: 1.55,
      colorA: "#5AB0FF",
      colorB: "#B794FF",
      colorC: "#FF9AD4",
      colorD: "#FFE0A3",
      orbitY: true,
      orbitSpeedY: 0.16,
      transmission: 0.22,
      iridescence: 1,
    },
  },
  {
    id: "deepgram",
    name: "Deepgram",
    builtin: true,
    swatches: ["#22D3EE", "#6366F1", "#34D399"],
    settings: {
      ...defaultSettings,
      shapeType: "torus",
      organic: 0.06,
      tubeRadius: 0.3,
      colorA: "#22D3EE",
      colorB: "#6366F1",
      colorC: "#818CF8",
      colorD: "#34D399",
      glow: 1.5,
      keyColor: "#67E8F9",
      rimColor: "#4ADE80",
      fillColor: "#A5B4FC",
    },
  },
  {
    id: "noise-flow",
    name: "Noise Flow",
    builtin: true,
    swatches: ["#38BDF8", "#A78BFA", "#F472B6"],
    settings: {
      ...defaultSettings,
      shapeType: "organic",
      noise: 0.28,
      noiseScale: 2.4,
      animateNoise: true,
      organic: 0.22,
      glow: 1.6,
      animateColors: true,
      colorSpeed: 0.55,
      speed: 0.8,
    },
  },
  {
    id: "twisted",
    name: "Twisted Ribbon",
    builtin: true,
    swatches: ["#818CF8", "#E879F9", "#FB7185"],
    settings: {
      ...defaultSettings,
      shapeType: "organic",
      tubeRadius: 0.22,
      twist: 420,
      twistAxis: "y",
      animateTwist: true,
      organic: 0.16,
      glow: 1.35,
      colorA: "#818CF8",
      colorB: "#C084FC",
      colorC: "#E879F9",
      colorD: "#FB7185",
    },
  },
  {
    id: "plasma-knot",
    name: "Plasma Knot",
    builtin: true,
    swatches: ["#22D3EE", "#A855F7", "#FB7185"],
    settings: {
      ...defaultSettings,
      shapeType: "knot",
      p: 3,
      q: 2,
      majorRadius: 1.05,
      tubeRadius: 0.28,
      noise: 0.05,
      glow: 1.7,
      orbitY: true,
      orbitX: true,
      orbitSpeedX: 0.08,
      colorA: "#22D3EE",
      colorB: "#818CF8",
      colorC: "#D946EF",
      colorD: "#FB7185",
    },
  },
  {
    id: "aurora",
    name: "Aurora",
    builtin: true,
    swatches: ["#34D399", "#22D3EE", "#A78BFA"],
    settings: {
      ...defaultSettings,
      shapeType: "torus",
      organic: 0.18,
      animateColors: true,
      colorSpeed: 0.7,
      glow: 1.65,
      iridescence: 1,
      colorA: "#34D399",
      colorB: "#22D3EE",
      colorC: "#818CF8",
      colorD: "#C084FC",
      keyColor: "#6EE7B7",
      rimColor: "#A78BFA",
      speed: 0.4,
      float: true,
    },
  },
  {
    id: "inferno",
    name: "Inferno",
    builtin: true,
    swatches: ["#F97316", "#EF4444", "#FBBF24"],
    settings: {
      ...defaultSettings,
      shapeType: "organic",
      organic: 0.14,
      noise: 0.1,
      glow: 1.8,
      colorA: "#FBBF24",
      colorB: "#F97316",
      colorC: "#EF4444",
      colorD: "#9F1239",
      keyColor: "#FDBA74",
      fillColor: "#FB7185",
      rimColor: "#F59E0B",
      animateGlow: true,
      bloomIntensity: 2.1,
    },
  },
  {
    id: "ice",
    name: "Ice Crystal",
    builtin: true,
    swatches: ["#E0F2FE", "#38BDF8", "#818CF8"],
    settings: {
      ...defaultSettings,
      shapeType: "torus",
      tubeRadius: 0.3,
      organic: 0.04,
      noise: 0.02,
      metalness: 0.55,
      roughness: 0.08,
      transmission: 0.28,
      glow: 1.2,
      colorA: "#E0F2FE",
      colorB: "#7DD3FC",
      colorC: "#38BDF8",
      colorD: "#818CF8",
      keyColor: "#E0F2FE",
      fillColor: "#93C5FD",
      rimColor: "#A5B4FC",
      animateColors: false,
    },
  },
  {
    id: "seesaw",
    name: "See-Saw",
    builtin: true,
    swatches: ["#60A5FA", "#A78BFA", "#F472B6"],
    settings: {
      ...defaultSettings,
      seesaw: true,
      seesawAxis: "x",
      seesawAmount: 42,
      orbitY: false,
      animateBend: true,
      bend: 35,
      bendAxis: "z",
      speed: 0.7,
    },
  },
  {
    id: "bend-wave",
    name: "Bend Wave",
    builtin: true,
    swatches: ["#818CF8", "#F472B6", "#FB923C"],
    settings: {
      ...defaultSettings,
      animateBend: true,
      bend: 150,
      bendAxis: "z",
      speed: 0.45,
      orbitY: true,
      orbitSpeedY: 0.06,
      glow: 1.5,
    },
  },
  {
    id: "liquid",
    name: "Liquid Glass",
    builtin: true,
    swatches: ["#67E8F9", "#C4B5FD", "#F9A8D4"],
    settings: {
      ...defaultSettings,
      shapeType: "organic",
      organic: 0.2,
      noise: 0.08,
      transmission: 0.42,
      roughness: 0.08,
      metalness: 0.05,
      clearcoat: 1,
      glow: 1.25,
      iridescence: 1,
      colorA: "#67E8F9",
      colorB: "#A5B4FC",
      colorC: "#F0ABFC",
      colorD: "#F9A8D4",
    },
  },
];

export function pickSettings(s: SophiaSettings): SophiaSettings {
  return { ...s };
}
